services:
  composer-app:
    container_name: redis-db_php8.4-runner
    image: redis-db:php8.4-runner
    build:
      context: ../../   # Navigate to the project root from bin/docker
      dockerfile: bin/docker/composer-app/Dockerfile
    ports:
      - "3000:8080"     # Port for laravel app
    volumes:
      - ../../:/app     # Mount the project root to /app in the container
    pull_policy: never

  frontend:
    container_name: redis-db_frontend
    image: redis-db:frontend
    build:
      context: ../../
      dockerfile: bin/docker/frontend/Dockerfile
    ports:
      - "5173:5173"     # Port for vite
    volumes:
      - ../../:/app
    pull_policy: never

  redis:
    container_name: redis-db_redis
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

  redis-insight:
    container_name: redis-db_redis-insight
    image: redis/redisinsight:latest
    ports:
      - "8001:5540"
    depends_on:
      - redis
    restart: unless-stopped

  redis-insight-init:
    image: curlimages/curl:latest
    environment:
      REDIS_INSIGHT_DB_NAME: task-tracker
      REDIS_INSIGHT_DB_HOST: redis
      REDIS_INSIGHT_DB_PORT: 6379
    volumes:
      - ./redis-insight-init/entrypoint.sh:/entrypoint.sh
    entrypoint: ["/bin/sh", "/entrypoint.sh"]
    depends_on:
      - redis-insight

volumes:
  redis-data:
