services:
  composer-app:
    container_name: redis-db_php8.4-runner
    image: redis-db:php8.4-runner
    build:
      context: ../../   # Navigate to the project root from bin/docker
      dockerfile: bin/docker/composer-app/Dockerfile
    ports:
      - "8080:8080"     # Port for laravel app
    volumes:
      - ../../:/app     # Mount the project root to /app in the container
    pull_policy: never

  frontend:
    container_name: redis-db_frontend
    image: redis-db:frontend
    build:
      context: ../../
      dockerfile: bin/docker/frontend/Dockerfile
    ports:
      - "5173:5173"     # Port for vite
    volumes:
      - ../../:/app
    pull_policy: never

  redis:
    container_name: redis-db_redis
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  redis-commander:
    container_name: redis-db_redis-commander
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
